config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'homes/top'
  get 'homes/about'
  resources :books
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length:{maximum:200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length:{minimum:2, maximum:20}
  validates :introduction, length:{maximum:50}

  has_one_attached :profile_image
  has_many :books, dependent: :destroy

  def get_image
    if image.attached?
      image
    else
      'bookers2-noimage'
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/bookers2-noimage.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    homes_top_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      #flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end



  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     # flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    #flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body )
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @newbook = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      #flash[:notice] = "You have updated user successfully.."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this book from being saved
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: book_path(@book.id) , method: :patch do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit "Update Book" %>

<%= link_to "Show", book_path(@book) %>
<%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
<div id="error_explanation">
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<h1>Books#index</h1>
<div class="row">
  <div class="col-md-3">

<h2>User info</h2>
<p><%= image_tag @user.get_profile_image(100,100) %></p>
<th>
  <tr>name</tr>
  <tr><%= @user.name %></tr>
</th>
<p>introduction</p>
<a><%= link_to "edit", edit_user_path(@user) %></a>


<h2>New book</h2>
<%=  form_with model: @book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

  </div>

  <div class="col-md-8 offset-md-1">
 <h2>Books</h2>
    <table>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
        </tr>
      <% @books.each do |book| %>
      <tbody>
        <tr>
          <td><%= image_tag @user.get_profile_image(100,100) %></td>
          <td>
            <%= link_to book.title, book_path(book.id)%>
          </td>
          <td>
            <%= book.body %>
          </td>
        </tr>
      </tbody>

      <% end %>
    </table>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>
<div class="row">
  <div class="col-md-3">

<h2>User info</h2>
<p><%= image_tag @user.get_profile_image(100,100) %></p>
<th>
  <tr>name</tr>
  <tr><%= @user.name %></tr>
</th>
<p>introduction</p>
<a><%= link_to "edit", edit_user_path(@user) %></a>


<h2>New book</h2>
<%=  form_with model: @newbook do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

  </div>

  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>

<p><%= @book.title %></p>
<p><%= @book.body %></p>

<% if @user == current_user %>
    <%= link_to "Edit", edit_book_path(@book.id)%>
    <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" %>
<% end %>
  </div>
</div>

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<h1>Welcome to Bookers!</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">


    <h1>welcome to Bookers !!</h1>
    <p>In Bookers,</p>
    <p>you can share and exchange your opinions , inpressions , and emotions about various books!</p>

    <div class="row">
      <%= link_to "Log in", new_user_session_path %>
    </div>
    <div class="row">
      <%= link_to "Sign up", new_user_registration_path %>
    </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <%= link_to "Bookers", homes_top_path %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
    <header>
      <% if user_signed_in? %>
        <li>
          <%= link_to "Home", user_path(current_user) %>
        </li>
        <li>
          <%= link_to "Users ", users_path %>
        </li>
        <li>
          <%= link_to "Books", books_path %>
        </li>
        <li>
          <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "Home", homes_top_path %>
        </li>
        <li>
          <%= link_to "About", homes_about_path %>
        </li>
        <li>
          <%= link_to "Sign up", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "Log in", new_user_session_path %>
        </li>
      <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

  <main class="mb-auto">
    <div class="container">
    <%= yield %>
    </div>
  </main>

    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container mt-5r">
        <div class="row no-gutters">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

  <h2>User info</h2>

<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this book from being saved
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <%= form_with model: @user, url: user_path(@user.id) , method: :patch do |f| %>

    <label for="inputName">Name</label>
    <div class="form-group">
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%></div>

    <label for="inputImage">Image</label>
    <div class="form-group">
      <%= f.file_field :profile_image, placeholder: "画像", accept: "image/*" %></div>

    <label for="inputIntroduction">Introduction</label>
    <div class="form-group">
      <%= f.text_field :Introduction,  id:"inputIntroduction", placeholder:"説明" %></div>

    <div class="form-group"><%= f.submit "Update User" %></div>
  <% end %>
  </div>
</div>

<div></div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-3">

<h2>User info</h2>
<p><%= image_tag @user.get_profile_image(100,100) %></p>
<th>
  <tr>name</tr>
  <tr><%= @user.name %></tr>
</th>
<p>introduction</p>
<a><%= link_to "edit", edit_user_path(@user) %></a>


<h2>New book</h2>
<%=  form_with model: @book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
        </tr>

    <% @users.each do |user| %>
      <tbody>
        <tr>
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
          <td><%= link_to "show", user_path(user.id) %></td>
        </tr>
      </tbody>
    <% end %>
      </thead>
    </table>

  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">

<h2>User info</h2>
<p><%= image_tag @user.get_profile_image(100,100) %></p>
<th>
  <tr>name</tr>
  <tr><%= @user.name %></tr>
</th>
<p>introduction</p>
<a><%= link_to "edit", edit_user_path(@user) %></a>


<h2>New book</h2>
<%=  form_with model: @newbook do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table>
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
        </tr>

    <% @books.each do |book| %>
      <tbody>
        <tr>
          <td><%= image_tag @user.get_profile_image(100,100) %></td>
          <td><%= link_to book.title, book_path(book) %></td>
          <td><%= book.body %></td>
        </tr>
      </tbody>
    <% end %>
      </thead>
    </table>

  </div>
</div>